UNIT_DIRECTIVE_INDEX = 0
BUILDING_DIRECTIVE_INDEX = 1
DISTRICT_DIRECTIVE_INDEX = 2

GOV_WIDE_HASH = GameInfo.Buildings["BUILDING_GOV_WIDE"].Hash
MONUMENT_HASH = GameInfo.Buildings["BUILDING_MONUMENT"].Hash

FOREIGN_TRADE_INDEX = GameInfo.Civics["CIVIC_FOREIGN_TRADE"].Index

COMMERCIAL_HUB_DISTRICT_INDEX = GameInfo.Districts["DISTRICT_COMMERCIAL_HUB"].Index
DIPLOMATIC_QUARTER_DISTRICT_INDEX = GameInfo.Districts["DISTRICT_DIPLOMATIC_QUARTER"].Index
HOLY_SITE_DISTRICT_INDEX = GameInfo.Districts["DISTRICT_HOLY_SITE"].Index
WONDER_INDEX = GameInfo.Districts["DISTRICT_WONDER"].Index

CLASSICAL_ERA_INDEX = GameInfo.Eras["ERA_CLASSICAL"].Index

BREAD_AND_CIRCUSES_HASH = GameInfo.Projects["PROJECT_BREAD_AND_CIRCUSES"].Hash
CARBON_RECAPTURE_HASH = GameInfo.Projects["PROJECT_CARBON_RECAPTURE"].Hash
RECOMMISSION_REACTOR_HASH = GameInfo.Projects["PROJECT_RECOMMISSION_REACTOR"].Hash

BORDER_CONTROL_HASH = GameInfo.Resolutions["WC_RES_BORDER_CONTROL"].Hash

BUILDER_HASH = GameInfo.Units["UNIT_BUILDER"].Hash

YIELD_GOLD = GameInfo.Yields["YIELD_GOLD"].Index

PARAM_BUILDING_TYPE = CityOperationTypes.PARAM_BUILDING_TYPE
PARAM_DISTRICT_TYPE = CityOperationTypes.PARAM_DISTRICT_TYPE
PARAM_PROJECT_TYPE = CityOperationTypes.PARAM_PROJECT_TYPE
PARAM_UNIT_TYPE = CityOperationTypes.PARAM_UNIT_TYPE

PARAM_X = CityOperationTypes.PARAM_X
PARAM_Y = CityOperationTypes.PARAM_Y

PARAM_INSERT_MODE = CityOperationTypes.PARAM_INSERT_MODE
PARAM_QUEUE_DESTINATION_LOCATION = CityOperationTypes.PARAM_QUEUE_DESTINATION_LOCATION

VALUE_APPEND = CityOperationTypes.VALUE_APPEND
VALUE_PREPEND = CityOperationTypes.VALUE_PREPEND
VALUE_REPLACE_AT = CityOperationTypes.VALUE_REPLACE_AT

print("=== Auto Production Queue (Constants) Loaded ===")
